name: Start

on:
   push:
   gollum:
   schedule:
       - cron: '30 17 * * *'

jobs:
  one:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with Maven
      env:
        BARK: ${{ secrets.BARK }}
        UID: ${{ secrets.UID }}
        UCODE: ${{ secrets.UCODE }}
      run: |
        mvn compile exec:java -Dexec.mainClass="starlight.Run" -Dexec.args="${BARK} ${UID} ${UCODE}"